[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
mrpiz_bindings = { path = "../mrpiz_bindings" }
log = { workspace = true }
env_logger = { workspace = true }
chrono = { workspace = true }
lazy_static = { workspace = true }
libc = { workspace = true } 