[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
mrpiz_bindings = { path = "../mrpiz_bindings" }
log = { workspace = true }
chrono = { workspace = true }
once_cell = "1.19"
parking_lot = "0.12"