name: Mirroring to Gitlab

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Ajout de /etc/hosts
        run: echo "172.24.7.8 gitlab-etu.openstack.etudis.eseo.fr" | sudo tee -a /etc/hosts

      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitlab-etu.openstack.etudis.eseo.fr:fisa-ise/pato/2025-2026/forcepushrebels/c.git
