name: Mirroring to Gitlab

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Nécessaire pour récupérer toutes les branches et tags

      - name: Ajout de /etc/hosts
        run: echo "172.24.7.8 gitlab-etu.openstack.etudis.eseo.fr" | sudo tee -a /etc/hosts

      - name: Push to GitLab
        run: |
          git remote add gitlab git@gitlab-etu.openstack.etudis.eseo.fr:fisa-ise/pato/2025-2026/forcepushrebels/c.git
          git push --mirror -f gitlab
