name: Mirroring to Gitlab

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: self-hosted
    steps:
      - name: Mirror repository to GitLab
        run: |
          echo $USER
          REPO_NAME=APP_CORE
          REPO_PATH=/home/pato/repos_github/$REPO_NAME
          
          # Vérifier si le dossier existe déjà
          if [ -d "$REPO_PATH" ]; then
            echo "Le dépôt existe déjà, mise à jour..."
            cd $REPO_PATH
            git fetch --all --prune
            git fetch --tags --force
          else
            echo "Clonage du dépôt..."
            mkdir -p /home/pato/repos_github
            git clone --mirror git@github.com:ForcePushRebels/$REPO_NAME.git $REPO_PATH
            cd $REPO_PATH
          fi
          
          # Configurer le remote GitLab s'il n'existe pas déjà
          if ! git remote get-url gitlab > /dev/null 2>&1; then
            git remote add gitlab git@gitlab-etu.openstack.etudis.eseo.fr:fisa-ise/pato/2025-2026/forcepushrebels/c.git
          fi
          
          # Pousser toutes les branches
          echo "Envoi de toutes les branches vers GitLab..."
          git push --force gitlab --all
          
          # Pousser tous les tags
          echo "Envoi de tous les tags vers GitLab..."
          git push --force gitlab --tags
